# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2
  codecov: codecov/codecov@4.0.1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
jobs:
  # A build job to build the ts project.
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run compile
  
  test:
    executor: node/default
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: test
          command: node test
      - codecov/upload

workflows:
  build-test:
      jobs:
      - build
      - test:
          matrix:
            parameters:
              node-version: ["18.20.2","lts","node-current"]
          requires:
            - build
          filters:
            branches:
              only: ['main', 'Release/**/*']
