name: Docinator
on:
  push:
    branches:
      - main
jobs:
  generate-wiki:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Generate documentation
        run: npm run build:wiki
      - name: Run Git update
        run: |
          chmod +x .github/scripts/git-update.sh
          bash .github/scripts/git-update.sh --branch-base bot/wiki_update_ --message "docs: updated wiki by github-actions-bot"
      - name: Create pull request
        uses: actions/github-script@v7
        id: pull-request
        with:
          script: |
            github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '[DOCS] WIKI update',
                head: '{{ env.BRANCH_NAME }}',
                base: context.ref,
                body: 'This is an automated pull request to update the wiki.'
            })
